# Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data3 = pd.read_excel('data/Data_Altar_120326_corrected.xlsx')
data2 = pd.read_excel('data/Data_Altar_21112025_corrected.xlsx')
data1 = pd.read_excel('data/Data_Altar_140225_corrected.xlsx')

In [3]:
data = pd.concat([data1, data2, data3])

In [4]:
SCOL_data = data[data['SampleType'] == "San Carlos Olivine (olivine): 0820M"]
SCOL_data.to_excel('./data/SCOL_data.xlsx', index=False)

In [5]:
data = data[data['SampleType'] != "San Carlos Olivine (olivine): 0820M"]
data = data.reset_index(drop=True)
data

,ID,Discard,dateTimeMeasured,Analyst,MassSpectrometer,SampleName,SampleType,d17O,d18O,d18OError,...,CapD17OError,IntensityReference,IntensitySample,SampleMass,TCDout,cd_d18O,cd_D17O,dp18O,dp17O,cd_d17O
0,18535,No,2025-02-14 11:28:49,Tommaso Di Rocco,MAT253Plus,wholeD2004-11_pos11,Mafic volcanics,2.951,5.742,0.002,...,4,4966,4963,2.081,46.304247,5.851200,-51.4,5.834148,3.029030,3.033622
1,18534,No,2025-02-14 09:39:36,Tommaso Di Rocco,MAT253Plus,wholeD2004-3_pos04,Mafic volcanics,2.792,5.439,0.002,...,4,4982,4987,1.920,40.128417,5.548200,-51.4,5.532865,2.869953,2.874075
2,18533,No,2025-02-14 06:01:17,Tommaso Di Rocco,MAT253Plus,cpxD2004-12_pos10,Clinopyroxene,2.626,5.127,0.002,...,4,4875,4929,1.715,46.877343,5.236200,-52.4,5.222539,2.705100,2.708763
3,18532,No,2025-02-14 04:08:18,Tommaso Di Rocco,MAT253Plus,opxD2004-4_pos07,Orthopyroxene,3.360,6.534,0.002,...,4,4988,4997,2.050,55.190951,6.643200,-59.4,6.621231,3.436610,3.442522
4,18531,No,2025-02-14 02:19:02,Tommaso Di Rocco,MAT253Plus,cpxD2004-4_pos06,Clinopyroxene,3.159,6.136,0.002,...,5,4969,4971,1.663,45.134658,6.245200,-53.4,6.225780,3.233812,3.239046
5,18529,No,2025-02-13 22:40:36,Tommaso Di Rocco,MAT253Plus,cpxD2004-5_pos05,Clinopyroxene,3.065,5.950,0.002,...,3,4984,4978,2.019,55.479469,6.059200,-47.4,6.040917,3.142204,3.147146
6,18528,No,2025-02-13 20:51:13,Tommaso Di Rocco,MAT253Plus,olivineD2004-11_pos09,Olivine,2.605,5.097,0.002,...,3,4940,4931,2.040,53.897045,5.206200,-58.4,5.192695,2.683343,2.686946
7,18527,No,2025-02-13 19:01:51,Tommaso Di Rocco,MAT253Plus,olivineD2004-3_pos08,Olivine,2.446,4.781,0.002,...,5,5000,5004,1.402,38.549035,4.890200,-50.4,4.878282,2.525333,2.528524
8,20975,No,2025-11-22 10:19:00,Tommaso Di Rocco,MAT253Plus,D2004-12-bulk_pos12,Mafic volcanics,2.482,4.853,0.002,...,5,4684,4723,1.812,58.343725,4.944167,-58.5,4.931984,2.545588,2.548831
9,20974,No,2025-11-22 08:38:00,Tommaso Di Rocco,MAT253Plus,D2004-8-bulk_pos11,Mafic volcanics,3.028,5.884,0.002,...,5,4975,4962,2.290,91.250722,5.975167,-55.5,5.957386,3.090000,3.094779
10,20971,No,2025-11-22 03:36:00,Tommaso Di Rocco,MAT253Plus,D2004-5-bulk_pos08,Mafic volcanics,3.227,6.255,0.002,...,5,4976,4968,1.865,78.215605,6.346167,-52.5,6.326115,3.287688,3.293099
11,21707,No,2026-03-12 11:09:43,Tommaso Di Rocco,MAT253Plus,N-W-1_pos12,Mafic plutonics,2.545,4.964,0.002,...,3,4919,4955,1.870,101.017778,4.843200,-60.0,4.831509,2.491037,2.494142
12,21706,No,2026-03-12 06:59:35,Tommaso Di Rocco,MAT253Plus,N-H-1_pos11,Mafic volcanics,2.543,4.941,0.002,...,5,4951,4948,1.815,101.458666,4.820200,-50.0,4.808620,2.488951,2.492051
13,21704,No,2026-03-12 03:43:42,Tommaso Di Rocco,MAT253Plus,D2004_7_pos09,Mafic volcanics,2.962,5.747,0.002,...,4,4915,4903,1.810,67.372657,5.626200,-55.0,5.610432,2.907308,2.911538
14,21708,No,2026-03-12 12:49:47,Tommaso Di Rocco,MAT253Plus,N-W-1-ol_pos13,Olivine,2.665,5.186,0.003,...,5,4961,4957,2.130,113.279657,5.065200,-57.0,5.052415,2.610675,2.614086

In [81]:
Develidag = data.drop([11, 12, 14])
Develidag = Develidag.reset_index(drop=True)
Develidag

,ID,Discard,dateTimeMeasured,Analyst,MassSpectrometer,SampleName,SampleType,d17O,d18O,d18OError,...,CapD17OError,IntensityReference,IntensitySample,SampleMass,TCDout,cd_d18O,cd_D17O,dp18O,dp17O,cd_d17O
0,18535,No,2025-02-14 11:28:49,Tommaso Di Rocco,MAT253Plus,wholeD2004-11_pos11,Mafic volcanics,2.951,5.742,0.002,...,4,4966,4963,2.081,46.304247,5.851200,-51.4,5.834148,3.029030,3.033622
1,18534,No,2025-02-14 09:39:36,Tommaso Di Rocco,MAT253Plus,wholeD2004-3_pos04,Mafic volcanics,2.792,5.439,0.002,...,4,4982,4987,1.920,40.128417,5.548200,-51.4,5.532865,2.869953,2.874075
2,18533,No,2025-02-14 06:01:17,Tommaso Di Rocco,MAT253Plus,cpxD2004-12_pos10,Clinopyroxene,2.626,5.127,0.002,...,4,4875,4929,1.715,46.877343,5.236200,-52.4,5.222539,2.705100,2.708763
3,18532,No,2025-02-14 04:08:18,Tommaso Di Rocco,MAT253Plus,opxD2004-4_pos07,Orthopyroxene,3.360,6.534,0.002,...,4,4988,4997,2.050,55.190951,6.643200,-59.4,6.621231,3.436610,3.442522
4,18531,No,2025-02-14 02:19:02,Tommaso Di Rocco,MAT253Plus,cpxD2004-4_pos06,Clinopyroxene,3.159,6.136,0.002,...,5,4969,4971,1.663,45.134658,6.245200,-53.4,6.225780,3.233812,3.239046
5,18529,No,2025-02-13 22:40:36,Tommaso Di Rocco,MAT253Plus,cpxD2004-5_pos05,Clinopyroxene,3.065,5.950,0.002,...,3,4984,4978,2.019,55.479469,6.059200,-47.4,6.040917,3.142204,3.147146
6,18528,No,2025-02-13 20:51:13,Tommaso Di Rocco,MAT253Plus,olivineD2004-11_pos09,Olivine,2.605,5.097,0.002,...,3,4940,4931,2.040,53.897045,5.206200,-58.4,5.192695,2.683343,2.686946
7,18527,No,2025-02-13 19:01:51,Tommaso Di Rocco,MAT253Plus,olivineD2004-3_pos08,Olivine,2.446,4.781,0.002,...,5,5000,5004,1.402,38.549035,4.890200,-50.4,4.878282,2.525333,2.528524
8,20975,No,2025-11-22 10:19:00,Tommaso Di Rocco,MAT253Plus,D2004-12-bulk_pos12,Mafic volcanics,2.482,4.853,0.002,...,5,4684,4723,1.812,58.343725,4.944167,-58.5,4.931984,2.545588,2.548831
9,20974,No,2025-11-22 08:38:00,Tommaso Di Rocco,MAT253Plus,D2004-8-bulk_pos11,Mafic volcanics,3.028,5.884,0.002,...,5,4975,4962,2.290,91.250722,5.975167,-55.5,5.957386,3.090000,3.094779
10,20971,No,2025-11-22 03:36:00,Tommaso Di Rocco,MAT253Plus,D2004-5-bulk_pos08,Mafic volcanics,3.227,6.255,0.002,...,5,4976,4968,1.865,78.215605,6.346167,-52.5,6.326115,3.287688,3.293099
11,21704,No,2026-03-12 03:43:42,Tommaso Di Rocco,MAT253Plus,D2004_7_pos09,Mafic volcanics,2.962,5.747,0.002,...,4,4915,4903,1.810,67.372657,5.626200,-55.0,5.610432,2.907308,2.911538

In [82]:
Develidag.to_excel('data/Develidag.xlsx', index=False)

In [83]:
Develidag_bulk = Develidag[Develidag['SampleType'] == "Mafic volcanics "]
Develidag_bulk

,ID,Discard,dateTimeMeasured,Analyst,MassSpectrometer,SampleName,SampleType,d17O,d18O,d18OError,...,CapD17OError,IntensityReference,IntensitySample,SampleMass,TCDout,cd_d18O,cd_D17O,dp18O,dp17O,cd_d17O
0,18535,No,2025-02-14 11:28:49,Tommaso Di Rocco,MAT253Plus,wholeD2004-11_pos11,Mafic volcanics,2.951,5.742,0.002,...,4,4966,4963,2.081,46.304247,5.851200,-51.4,5.834148,3.029030,3.033622
1,18534,No,2025-02-14 09:39:36,Tommaso Di Rocco,MAT253Plus,wholeD2004-3_pos04,Mafic volcanics,2.792,5.439,0.002,...,4,4982,4987,1.920,40.128417,5.548200,-51.4,5.532865,2.869953,2.874075
8,20975,No,2025-11-22 10:19:00,Tommaso Di Rocco,MAT253Plus,D2004-12-bulk_pos12,Mafic volcanics,2.482,4.853,0.002,...,5,4684,4723,1.812,58.343725,4.944167,-58.5,4.931984,2.545588,2.548831
9,20974,No,2025-11-22 08:38:00,Tommaso Di Rocco,MAT253Plus,D2004-8-bulk_pos11,Mafic volcanics,3.028,5.884,0.002,...,5,4975,4962,2.290,91.250722,5.975167,-55.5,5.957386,3.090000,3.094779
10,20971,No,2025-11-22 03:36:00,Tommaso Di Rocco,MAT253Plus,D2004-5-bulk_pos08,Mafic volcanics,3.227,6.255,0.002,...,5,4976,4968,1.865,78.215605,6.346167,-52.5,6.326115,3.287688,3.293099
11,21704,No,2026-03-12 03:43:42,Tommaso Di Rocco,MAT253Plus,D2004_7_pos09,Mafic volcanics,2.962,5.747,0.002,...,4,4915,4903,1.810,67.372657,5.626200,-55.0,5.610432,2.907308,2.911538